import { Styles } from "../widgets/styles.slint";
import {UiState} from "../blocks/globals.slint";
import { Button } from "../widgets/button.slint";

export component ConnectionsPage inherits Rectangle {
    background: transparent;

    in-out property <bool> allowed: false;

    VerticalLayout {
        padding: Styles.sizes.p-xl * 2;
        spacing: Styles.sizes.s-md;

        HorizontalLayout {
            spacing: Styles.sizes.s-md;

            VerticalLayout {
                alignment: LayoutAlignment.center;
                padding: Styles.sizes.p-xl;

                Image {
                    source: UiState.page == "default-scope" ? @image-url("../assets/globe-star.svg") : @image-url("../assets/globe-sync.svg");
                    colorize: Styles.palette.window-fg;
                    width: 32px;
                    height: 32px;
                }
            }

            VerticalLayout {
                spacing: Styles.sizes.s-md;
                alignment: LayoutAlignment.center;
                horizontal-stretch: 1;

                Text {
                    text: UiState.page == "default-scope" ? @tr("Default Scope") : "";
                    font-size: Styles.sizes.font;
                    font-weight: 700;
                    color: Styles.palette.window-fg;
                }

                Text {
                    text: UiState.page;
                    font-size: Styles.sizes.font;
                    font-weight: 400;
                    color: Styles.palette.window-fg;
                    opacity: 0.6;
                }
            }

            VerticalLayout {
                spacing: Styles.sizes.s-md;
                alignment: LayoutAlignment.center;

                Text {
                    text: UiState.page == "default-scope" ? @tr("Manually Controlled") : @tr("External Controlled");
                    font-size: Styles.sizes.font;
                    color: UiState.page == "default-scope" ? Styles.palette.info-bg : Styles.palette.success-bg;
                    horizontal-alignment: right;
                }

                Text {
                    text: "HTTP/1, HTTP/2";
                    font-size: Styles.sizes.font;
                    font-weight: 400;
                    color: Styles.palette.window-fg;
                    opacity: 0.6;
                    horizontal-alignment: right;
                }
            }

            Rectangle {
                width: Styles.sizes.p-md;
            }
        }

        Rectangle {
            height: 1px;
            background: Styles.palette.layer-3;
        }

        HorizontalLayout {

            Rectangle {
                width: Styles.sizes.p-md;
            }

            Text {
                text: UiState.page == "default-scope" ? @tr("This scope is controlled by you manually.") : (root.allowed ? @tr("This domain can control wsrx on your local network.") : @tr("This domain requested controlling wsrx."));
                color: UiState.page == "default-scope" ? Styles.palette.info-bg : (root.allowed ? Styles.palette.success-bg : Styles.palette.error-bg);
                vertical-alignment: center;
                horizontal-stretch: 1;
            }

            if UiState.page == "default-scope": Button {
                icon: @image-url("../assets/checkmark-circle.svg");
                flat: true;
                text: @tr("Enjoy");
                icon-color: Styles.palette.success-bg;
                disabled: true;
            }

            if UiState.page != "default-scope" && !root.allowed: Button {
                icon: @image-url("../assets/checkmark-circle.svg");
                flat: true;
                text: @tr("Accept");
                icon-color: Styles.palette.success-bg;
            }

            if UiState.page != "default-scope" && !root.allowed: Button {
                icon: @image-url("../assets/dismiss-circle.svg");
                flat: true;
                text: @tr("Decline");
                icon-color: Styles.palette.error-bg;
            }

            if UiState.page != "default-scope" && root.allowed: Button {
                icon: @image-url("../assets/dismiss-circle.svg");
                flat: true;
                text: @tr("Remove");
                icon-color: Styles.palette.error-bg;
            }
        }

        Rectangle {
            height: 1px;
            background: Styles.palette.layer-3;
        }

        Flickable {
            vertical-stretch: 1;
        }
    }
}
